# Site settings
title: "首页"
url: "http://www.xiongfuli.com"
paginate: 10

author:
    name: Fuli
    github: Ihavee
    email:
    gitcafe: Havee
    twitter:
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
kramdown:
    input: GFM
permalink: /:categories/:year-:month/:title.html
gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, qrsync, Rakefile]
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed
# comment
comments:
    duoshuo:
        name: bearshng                              # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: 6da593142b14f78c0c00d3ff4964f8c7                            # 百度统计 js 代码后的字符串
webmaster:
    baidu:
        verify:
    google:
        verify:
    bing:
        verify:
